groups:
  - name: fastprep_outbox
    interval: 30s
    rules:
      - alert: OutboxHighFailureRate
        expr: increase(outbox_processed_total{status="failed"}[5m]) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Outbox worker has high failure rate"
          description: "{{ $value }} failed messages in last 5 minutes (threshold: 10)"

      - alert: OutboxAdapterLatencyHigh
        expr: histogram_quantile(0.95, rate(adapter_latency_seconds_bucket[5m])) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "TG Adapter latency is high"
          description: "p95 latency is {{ $value }}s (threshold: 5s)"

      - alert: OutboxWorkerDown
        expr: up{job="fastprep-admin-worker"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Outbox worker is down"
          description: "Worker metrics endpoint is unreachable"

